/*
 Navicat Premium Data Transfer

 Source Server         : IPPF3
 Source Server Type    : MySQL
 Source Server Version : 50537
 Source Host           : localhost
 Source Database       : test

 Target Server Type    : MySQL
 Target Server Version : 50537
 File Encoding         : utf-8

 Date: 01/15/2015 13:14:25 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `dim_client`
-- ----------------------------
DROP TABLE IF EXISTS `dim_client`;
CREATE TABLE `dim_client` (
  `client_key` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `client_id` bigint(20) DEFAULT NULL,
  `record_id` bigint(20) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `postal_code` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `country_code` varchar(255) DEFAULT NULL,
  `first_service_date` date DEFAULT NULL,
  `drivers_license` varchar(255) DEFAULT NULL,
  `social_security` varchar(255) DEFAULT NULL,
  `occupation` longtext,
  `phone_home` varchar(255) DEFAULT NULL,
  `phone_biz` varchar(255) DEFAULT NULL,
  `phone_cell` varchar(255) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `first_service_date_key` bigint(20) DEFAULT NULL,
  `external_client_id` varchar(255) DEFAULT NULL,
  `marital_status` varchar(255) DEFAULT NULL,
  `ethnicity` varchar(255) DEFAULT NULL,
  `living_children` varchar(255) DEFAULT NULL,
  `family_size` varchar(255) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `userlist1` varchar(255) DEFAULT NULL,
  `education` varchar(255) DEFAULT NULL,
  `userlist3` varchar(255) DEFAULT NULL,
  `userlist4` varchar(255) DEFAULT NULL,
  `religion` varchar(255) DEFAULT NULL,
  `userlist6` varchar(255) DEFAULT NULL,
  `residence` varchar(255) DEFAULT NULL,
  `referral_source` varchar(30) DEFAULT NULL,
  `price_level` varchar(255) DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `contraceptive_date` date DEFAULT NULL,
  PRIMARY KEY (`client_key`),
  KEY `idx_patient_key` (`client_key`)
) ENGINE=InnoDB AUTO_INCREMENT=32317 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_code`
-- ----------------------------
DROP TABLE IF EXISTS `dim_code`;
CREATE TABLE `dim_code` (
  `code_key` int(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `code` varchar(20) DEFAULT NULL,
  `code_type` varchar(15) DEFAULT NULL,
  `code_text` longtext,
  PRIMARY KEY (`code_key`),
  KEY `idx_code_key` (`code_key`),
  KEY `idx_code` (`code`),
  KEY `idx_code_type` (`code_type`)
) ENGINE=InnoDB AUTO_INCREMENT=3834 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_date`
-- ----------------------------
DROP TABLE IF EXISTS `dim_date`;
CREATE TABLE `dim_date` (
  `date_key` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `date` date DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `year_for_week` int(11) DEFAULT NULL,
  `year_for_week_iso8601` int(11) DEFAULT NULL,
  `quarter` int(11) DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `week_of_year` int(11) DEFAULT NULL,
  `week_of_year_iso8601` int(11) DEFAULT NULL,
  `week_of_month` int(11) DEFAULT NULL,
  `week_of_month_iso8601` int(11) DEFAULT NULL,
  `weekday_in_month` int(11) DEFAULT NULL,
  `day` int(11) DEFAULT NULL,
  `day_of_year` int(11) DEFAULT NULL,
  `day_of_week` int(11) DEFAULT NULL,
  `date_iso` tinytext,
  `days_in_month` int(11) DEFAULT NULL,
  `days_in_year` int(11) DEFAULT NULL,
  `days_in_quarter` int(11) DEFAULT NULL,
  `is_leap_year` int(11) DEFAULT NULL,
  `is_weekend` int(11) DEFAULT NULL,
  `is_holiday` int(11) DEFAULT NULL,
  `holiday_name` tinytext,
  `is_working_day` int(11) DEFAULT NULL,
  `is_world_cup` int(11) DEFAULT NULL,
  `world_cup_country` tinytext,
  `day_of_week_long_label_eng` tinytext,
  `day_of_week_long_label_ger` tinytext,
  `day_of_week_short_label_eng` tinytext,
  `day_of_week_short_label_ger` tinytext,
  `month_long_label_eng` tinytext,
  `month_long_label_ger` tinytext,
  `month_short_label_eng` tinytext,
  `month_short_label_ger` tinytext,
  `days_in_year_for_week` int(11) DEFAULT NULL,
  `days_in_year_for_week_iso8601` int(11) DEFAULT NULL,
  `is_leap_year_for_week` int(11) DEFAULT NULL,
  `is_leap_year_for_week_iso8601` int(11) DEFAULT NULL,
  PRIMARY KEY (`date_key`),
  KEY `idx_date_key` (`date_key`),
  KEY `idx_year` (`year`),
  KEY `idx_month` (`month`)
) ENGINE=InnoDB AUTO_INCREMENT=15344 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_facility`
-- ----------------------------
DROP TABLE IF EXISTS `dim_facility`;
CREATE TABLE `dim_facility` (
  `facility_key` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` datetime DEFAULT NULL,
  `date_to` datetime DEFAULT NULL,
  `facility_id` int(11) DEFAULT NULL,
  `facility_name` varchar(255) DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `postal_code` varchar(11) DEFAULT NULL,
  `country_code` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`facility_key`),
  KEY `idx_facility_key` (`facility_key`),
  KEY `idx_facility_name` (`facility_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_referral`
-- ----------------------------
DROP TABLE IF EXISTS `dim_referral`;
CREATE TABLE `dim_referral` (
  `referral_key` int(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `referral_id` bigint(20) DEFAULT NULL,
  `client_id` bigint(20) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `referral_date` date DEFAULT NULL,
  `referred_by` int(11) DEFAULT NULL,
  `referred_to` int(11) DEFAULT NULL,
  `reply_date` date DEFAULT NULL,
  `external_referral` varchar(20) DEFAULT NULL,
  `requested_service` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`referral_key`),
  KEY `idx_referral_key` (`referral_key`),
  KEY `idx_patient_id` (`client_id`),
  KEY `idx_refer_from` (`referred_by`),
  KEY `idx_refer_to` (`referred_to`),
  KEY `idx_refer_external` (`external_referral`)
) ENGINE=InnoDB AUTO_INCREMENT=210 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_service`
-- ----------------------------
DROP TABLE IF EXISTS `dim_service`;
CREATE TABLE `dim_service` (
  `service_key` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` datetime DEFAULT NULL,
  `date_to` datetime DEFAULT NULL,
  `code_id` int(11) DEFAULT NULL,
  `billing_code` varchar(31) DEFAULT NULL,
  `code_text` varchar(255) DEFAULT NULL,
  `code_type` int(11) DEFAULT NULL,
  `code_type_key` varchar(15) DEFAULT NULL,
  `code_type_description` varchar(31) DEFAULT NULL,
  `superbill` varchar(31) DEFAULT NULL,
  `IPPF` tinytext,
  `IPPF2` tinytext,
  `IPPFCM` tinytext,
  `ACCT` tinytext,
  `ippf_code` text,
  `family_code` text,
  `family_desc` text,
  `sub_family_code` text,
  `sub_family_desc` text,
  `type_code` text,
  `type_group_desc` text,
  `type_desc` text,
  `service_detail_code` text,
  `complete_desc` text,
  PRIMARY KEY (`service_key`),
  KEY `idx_service_key` (`service_key`),
  KEY `idx_code_id` (`code_id`),
  KEY `idx_billing_code` (`billing_code`),
  KEY `idx_code_text` (`code_text`),
  KEY `idx_code_type` (`code_type`),
  KEY `idx_code_type_key` (`code_type_key`),
  KEY `idx_code_type_description` (`code_type_description`),
  KEY `idx_IPPF` (`IPPF`(10)),
  KEY `idx_IPPF2` (`IPPF2`(20)),
  KEY `idx_IPPFCM` (`IPPFCM`(10)),
  KEY `idx_ippf_code` (`ippf_code`(20)),
  KEY `idx_family_code` (`family_code`(10)),
  KEY `idx_family_desc` (`family_desc`(50)),
  KEY `idx_sub_family_code` (`sub_family_code`(10)),
  KEY `idx_sub_family_desc` (`sub_family_desc`(100)),
  KEY `idx_type_code` (`type_code`(10)),
  KEY `idx_type_group_desc` (`type_group_desc`(100)),
  KEY `idx_type_desc` (`type_desc`(100)),
  KEY `idx_service_detail_code` (`service_detail_code`(10)),
  KEY `idx_complete_desc` (`complete_desc`(200))
) ENGINE=InnoDB AUTO_INCREMENT=670 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `dim_user`
-- ----------------------------
DROP TABLE IF EXISTS `dim_user`;
CREATE TABLE `dim_user` (
  `user_key` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `version` int(11) DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `middle_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `facility_id` int(11) DEFAULT NULL,
  `specialty` varchar(255) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  `address` varchar(60) DEFAULT NULL,
  `city` varchar(30) DEFAULT NULL,
  `state` varchar(30) DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `taxonomy` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`user_key`),
  KEY `idx_user_key` (`user_key`),
  KEY `idx_first_name` (`first_name`),
  KEY `idx_last_name` (`last_name`),
  KEY `idx_organization` (`organization`),
  KEY `idx_facility_id` (`facility_id`)
) ENGINE=InnoDB AUTO_INCREMENT=132 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `fact_client_services`
-- ----------------------------
DROP TABLE IF EXISTS `fact_client_services`;
CREATE TABLE `fact_client_services` (
  `client_key` bigint(20) DEFAULT NULL,
  `facility_key` bigint(20) DEFAULT NULL,
  `service_key` bigint(20) DEFAULT NULL,
  `date_key` bigint(20) DEFAULT NULL,
  `encounter_id` bigint(20) DEFAULT NULL,
  `other_encounter_id` bigint(20) DEFAULT NULL,
  `referral_key` bigint(20) DEFAULT NULL,
  `invoice_refno` varchar(31) DEFAULT NULL,
  `pc_catid` int(11) DEFAULT NULL,
  `supervisor_id` int(11) DEFAULT NULL,
  `billing_id` int(11) DEFAULT NULL,
  `units` int(11) DEFAULT NULL,
  `billing_amount` double DEFAULT NULL,
  `first_encounter` char(1) DEFAULT NULL,
  `code_key` int(11) DEFAULT NULL,
  `provider_id` bigint(20) DEFAULT NULL,
  KEY `idx_patient_key` (`client_key`),
  KEY `idx_facility_key` (`facility_key`),
  KEY `idx_service_key` (`service_key`),
  KEY `idx_date_key` (`date_key`),
  KEY `idx_encounter_id` (`encounter_id`),
  KEY `idx_other_encounter_id` (`other_encounter_id`),
  KEY `idx_referral_key` (`referral_key`),
  KEY `idx_first_encounter` (`first_encounter`),
  KEY `idx_code_key` (`code_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `fact_contraception`
-- ----------------------------
DROP TABLE IF EXISTS `fact_contraception`;
CREATE TABLE `fact_contraception` (
  `contraception_id` bigint(20) DEFAULT NULL,
  `client_key` int(11) DEFAULT NULL,
  `date_key` int(11) DEFAULT NULL,
  `user_key` int(11) DEFAULT NULL,
  `create_date` date DEFAULT NULL,
  `encounter_id` bigint(20) DEFAULT NULL,
  `form_name` varchar(100) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `groupname` varchar(50) DEFAULT NULL,
  `authorized` varchar(3) DEFAULT NULL,
  `deleted` varchar(3) DEFAULT NULL,
  `curmethod` varchar(100) DEFAULT NULL,
  `mcreason` varchar(100) DEFAULT NULL,
  `newmauser` varchar(50) DEFAULT NULL,
  `newmethod` varchar(100) DEFAULT NULL,
  `pastmodern` varchar(50) DEFAULT NULL,
  `reqmethod` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `fact_ippf_gcac`
-- ----------------------------
DROP TABLE IF EXISTS `fact_ippf_gcac`;
CREATE TABLE `fact_ippf_gcac` (
  `ippf_gcac_id` bigint(20) DEFAULT NULL,
  `client_key` int(11) DEFAULT NULL,
  `date_key` int(11) DEFAULT NULL,
  `encounter_id` bigint(20) DEFAULT NULL,
  `form_name` varchar(100) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `groupname` varchar(50) DEFAULT NULL,
  `authorized` varchar(3) DEFAULT NULL,
  `deleted` varchar(3) DEFAULT NULL,
  `client_status` varchar(100) DEFAULT NULL,
  `ab_location` varchar(100) DEFAULT NULL,
  `in_ab_proc` varchar(100) DEFAULT NULL,
  `compl_incomp` varchar(100) DEFAULT NULL,
  `compl_bleed` varchar(100) DEFAULT NULL,
  `compl_trauma` varchar(100) DEFAULT NULL,
  `compl_shock` varchar(100) DEFAULT NULL,
  `compl_infect` varchar(100) DEFAULT NULL,
  `compl_ectopic` varchar(100) DEFAULT NULL,
  `compl_failed` varchar(100) DEFAULT NULL,
  `compl_other` varchar(100) DEFAULT NULL,
  `main_compl` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `fact_ippf_srh`
-- ----------------------------
DROP TABLE IF EXISTS `fact_ippf_srh`;
CREATE TABLE `fact_ippf_srh` (
  `ippf_srh_id` bigint(20) DEFAULT NULL,
  `client_key` bigint(20) DEFAULT NULL,
  `date_key` bigint(20) DEFAULT NULL,
  `encounter_id` bigint(20) DEFAULT NULL,
  `form_name` longtext,
  `username` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` varchar(4) DEFAULT NULL,
  `deleted` varchar(4) DEFAULT NULL,
  `menstrual_history` varchar(255) DEFAULT NULL,
  `blood_group` varchar(255) DEFAULT NULL,
  `rh_factor` varchar(255) DEFAULT NULL,
  `obstectric_history` varchar(255) DEFAULT NULL,
  `abortion_basic_history` varchar(255) DEFAULT NULL,
  `hiv_aids_basic_history` varchar(255) DEFAULT NULL,
  `its_itr_basic_history` varchar(255) DEFAULT NULL,
  `fertitility_basic_history` varchar(255) DEFAULT NULL,
  `abo_exams_ane_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_ane_val` tinytext,
  `abo_exams_bgr_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_bgr_val` tinytext,
  `abo_exams_ect_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_ect_val` tinytext,
  `abo_exams_cer_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_cer_val` tinytext,
  `abo_exams_hiv_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_hiv_val` tinytext,
  `abo_exams_oth_num` decimal(16,2) DEFAULT NULL,
  `abo_exams_oth_val` tinytext,
  `fer_causes_alc` tinytext,
  `fer_causes_ath` tinytext,
  `fer_causes_dep` tinytext,
  `fer_causes_dia` tinytext,
  `fer_causes_edy` tinytext,
  `fer_causes_end` tinytext,
  `fer_causes_hyp` tinytext,
  `fer_causes_ins` tinytext,
  `fer_causes_kid` tinytext,
  `fer_causes_med` tinytext,
  `fer_causes_msc` tinytext,
  `fer_causes_oth` tinytext,
  `fer_causes_pos` tinytext,
  `fer_causes_prc` tinytext,
  `fer_causes_smo` tinytext,
  `fer_causes_str` tinytext,
  `fer_exams_bas_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_bas_val` tinytext,
  `fer_exams_ccc_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_ccc_val` tinytext,
  `fer_exams_end_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_end_val` tinytext,
  `fer_exams_ftp_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_ftp_val` tinytext,
  `fer_exams_hor_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_hor_val` tinytext,
  `fer_exams_hsa_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_hsa_val` tinytext,
  `fer_exams_hsc_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_hsc_val` tinytext,
  `fer_exams_lap_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_lap_val` tinytext,
  `fer_exams_muc_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_muc_val` tinytext,
  `fer_exams_oth_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_oth_val` tinytext,
  `fer_exams_ova_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_ova_val` tinytext,
  `fer_exams_pct_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_pct_val` tinytext,
  `fer_exams_sem_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_sem_val` tinytext,
  `fer_exams_spc_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_spc_val` tinytext,
  `fer_exams_spg_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_spg_val` tinytext,
  `fer_exams_tes_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_tes_val` tinytext,
  `fer_exams_tve_num` decimal(16,2) DEFAULT NULL,
  `fer_exams_tve_val` tinytext,
  `fer_treat_emb` tinytext,
  `fer_treat_fer` tinytext,
  `fer_treat_git` tinytext,
  `fer_treat_ocd` tinytext,
  `fer_treat_oth` tinytext,
  `fer_treat_ovi` tinytext,
  `fer_treat_sem` tinytext,
  `fer_treat_zit` tinytext,
  `gest_age_by_lmp` tinytext,
  `gest_age_by_oth` tinytext,
  `gest_age_by_son` tinytext,
  `gyn_exams_bds_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_bds_val` tinytext,
  `gyn_exams_hys_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_hys_val` tinytext,
  `gyn_exams_img_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_img_val` tinytext,
  `gyn_exams_mam_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_mam_val` tinytext,
  `gyn_exams_man_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_man_val` tinytext,
  `gyn_exams_mbe_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_mbe_val` tinytext,
  `gyn_exams_mpe_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_mpe_val` tinytext,
  `gyn_exams_oth_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_oth_val` tinytext,
  `gyn_exams_pap_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_pap_val` tinytext,
  `gyn_exams_son_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_son_val` tinytext,
  `gyn_exams_tom_num` decimal(16,2) DEFAULT NULL,
  `gyn_exams_tom_val` tinytext,
  `hiv_exams_cd4_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_cd4_val` tinytext,
  `hiv_exams_eli_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_eli_val` tinytext,
  `hiv_exams_ifa_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_ifa_val` tinytext,
  `hiv_exams_oth_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_oth_val` tinytext,
  `hiv_exams_rat_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_rat_val` tinytext,
  `hiv_exams_uri_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_uri_val` tinytext,
  `hiv_exams_vil_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_vil_val` tinytext,
  `hiv_exams_wba_num` decimal(16,2) DEFAULT NULL,
  `hiv_exams_wba_val` tinytext,
  `its_exams_can_num` decimal(16,2) DEFAULT NULL,
  `its_exams_can_val` tinytext,
  `its_exams_cha_num` decimal(16,2) DEFAULT NULL,
  `its_exams_cha_val` tinytext,
  `its_exams_chl_num` decimal(16,2) DEFAULT NULL,
  `its_exams_chl_val` tinytext,
  `its_exams_gon_num` decimal(16,2) DEFAULT NULL,
  `its_exams_gon_val` tinytext,
  `its_exams_hep_num` decimal(16,2) DEFAULT NULL,
  `its_exams_hep_val` tinytext,
  `its_exams_hpv_num` decimal(16,2) DEFAULT NULL,
  `its_exams_hpv_val` tinytext,
  `its_exams_hsv_num` decimal(16,2) DEFAULT NULL,
  `its_exams_hsv_val` tinytext,
  `its_exams_oth_num` decimal(16,2) DEFAULT NULL,
  `its_exams_oth_val` tinytext,
  `its_exams_syp_num` decimal(16,2) DEFAULT NULL,
  `its_exams_syp_val` tinytext,
  `its_exams_tri_num` decimal(16,2) DEFAULT NULL,
  `its_exams_tri_val` tinytext,
  `its_exams_vag_num` decimal(16,2) DEFAULT NULL,
  `its_exams_vag_val` tinytext,
  `men_compl_abn` tinytext,
  `men_compl_bleed` tinytext,
  `men_compl_menpain` tinytext,
  `men_compl_nomen` tinytext,
  `men_compl_oth` tinytext,
  `men_compl_perpain` tinytext,
  `men_hist_bleed` tinytext,
  `men_hist_disch` tinytext,
  `men_hist_dysmen` tinytext,
  `men_hist_norflow` tinytext,
  `men_hist_norlen` tinytext,
  `men_hist_normen` tinytext,
  `men_hist_oth` tinytext,
  `obs_exams_fem_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_fem_val` tinytext,
  `obs_exams_fet_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_fet_val` tinytext,
  `obs_exams_pel_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_pel_val` tinytext,
  `obs_exams_pla_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_pla_val` tinytext,
  `obs_exams_pnc_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_pnc_val` tinytext,
  `obs_exams_son_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_son_val` tinytext,
  `obs_exams_utm_num` decimal(16,2) DEFAULT NULL,
  `obs_exams_utm_val` tinytext,
  `pap_hist_dtlast_opt` tinytext,
  `pap_hist_dtlast_val` tinytext,
  `pap_hist_dtnext_opt` tinytext,
  `pap_hist_dtnext_val` tinytext,
  `pap_hist_results_opt` tinytext,
  `pap_hist_results_val` tinytext,
  `pap_hist_treat_opt` tinytext,
  `pap_hist_treat_val` tinytext,
  `pr_compl_abrup` tinytext,
  `pr_compl_accr` tinytext,
  `pr_compl_bleed` tinytext,
  `pr_compl_bofum` tinytext,
  `pr_compl_cercl` tinytext,
  `pr_compl_chol` tinytext,
  `pr_compl_compl` tinytext,
  `pr_compl_confet` tinytext,
  `pr_compl_cpox` tinytext,
  `pr_compl_cytomeg` tinytext,
  `pr_compl_dia` tinytext,
  `pr_compl_dnc` tinytext,
  `pr_compl_ect` tinytext,
  `pr_compl_fasd` tinytext,
  `pr_compl_fgr` tinytext,
  `pr_compl_hafl` tinytext,
  `pr_compl_hiv` tinytext,
  `pr_compl_hyperm` tinytext,
  `pr_compl_incerv` tinytext,
  `pr_compl_iugr` tinytext,
  `pr_compl_lafl` tinytext,
  `pr_compl_list` tinytext,
  `pr_compl_mis` tinytext,
  `pr_compl_molar` tinytext,
  `pr_compl_pih` tinytext,
  `pr_compl_preecl` tinytext,
  `pr_compl_prev` tinytext,
  `pr_compl_rest` tinytext,
  `pr_compl_rhf` tinytext,
  `pr_compl_sga` tinytext,
  `pr_compl_sti` tinytext,
  `pr_compl_strep` tinytext,
  `pr_compl_tip` tinytext,
  `pr_compl_tox` tinytext,
  `pr_compl_uti` tinytext,
  `pr_compl_vag` tinytext,
  `pr_compl_vts` tinytext,
  `pr_compl_yeast` tinytext,
  `pr_outcome_abo` tinytext,
  `pr_outcome_ect` tinytext,
  `pr_outcome_live` tinytext,
  `pr_outcome_oth` tinytext,
  `pr_outcome_still` tinytext,
  `pr_status_a_ep` tinytext,
  `pr_status_a_mp` tinytext,
  `pr_status_dis` tinytext,
  `pr_status_n_bpe` tinytext,
  `pr_status_n_u` tinytext,
  `uro_disease_bal` tinytext,
  `uro_disease_cry` tinytext,
  `uro_disease_ect` tinytext,
  `uro_disease_edy` tinytext,
  `uro_disease_epd` tinytext,
  `uro_disease_eps` tinytext,
  `uro_disease_fre` tinytext,
  `uro_disease_hyd` tinytext,
  `uro_disease_hyp` tinytext,
  `uro_disease_mic` tinytext,
  `uro_disease_orc` tinytext,
  `uro_disease_par` tinytext,
  `uro_disease_pec` tinytext,
  `uro_disease_pef` tinytext,
  `uro_disease_pey` tinytext,
  `uro_disease_phi` tinytext,
  `uro_disease_prc` tinytext,
  `uro_disease_pre` tinytext,
  `uro_disease_prt` tinytext,
  `uro_disease_spe` tinytext,
  `uro_disease_tec` tinytext,
  `uro_disease_tet` tinytext,
  `uro_disease_var` tinytext,
  `uro_exams_cys` tinytext,
  `uro_exams_oth` tinytext,
  `uro_exams_pen` tinytext,
  `uro_exams_pro` tinytext,
  `uro_exams_ure` tinytext,
  `uro_exams_uro` tinytext
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
--  Table structure for `ippf_service_lookup`
-- ----------------------------
DROP TABLE IF EXISTS `ippf_service_lookup`;
CREATE TABLE `ippf_service_lookup` (
  `family_code` text,
  `family_desc` text,
  `sub_family_code` text,
  `sub_family_desc` text,
  `type_code` text,
  `type_group_desc` text,
  `type_desc` text,
  `service_detail_code` text,
  `complete_desc` text,
  `service_desc` text,
  `ippf_code` text,
  KEY `idx_family_code` (`family_code`(10)),
  KEY `idx_family_desc` (`family_desc`(50)),
  KEY `idx_sub_family_code` (`sub_family_code`(10)),
  KEY `idx_sub_family_desc` (`sub_family_desc`(100)),
  KEY `idx_type_code` (`type_code`(10)),
  KEY `idx_type_group_desc` (`type_group_desc`(100)),
  KEY `idx_type_desc` (`type_desc`(100)),
  KEY `idx_service_detail_code` (`service_detail_code`(10)),
  KEY `idx_complete_desc` (`complete_desc`(200)),
  KEY `idx_service_desc` (`service_desc`(200)),
  KEY `idx_ippf_code` (`ippf_code`(10))
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

SET FOREIGN_KEY_CHECKS = 1;
